name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # Puedes cambiar esto según la versión de Python que estés utilizando

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ajusta este comando según tus necesidades

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: abrahamramirezT_lambdas_back  # Reemplaza con la clave de tu proyecto en SonarCloud
          token: ${{ secrets.SONAR_TOKEN }}  # Asegúrate de haber configurado este secreto en tu repositorio
          scannerVersion: '4.4.0.2170'  # Puedes ajustar la versión del escáner según tu necesidad
