name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          projectKey: abrahamramirezT_lambdas_back
          token: ${{ secrets.SONAR_TOKEN }}
          scannerVersion: '4.4.0.2170'
          extraProperties: |
            sonar.sources=.
            sonar.exclusions=**/__pycache__/**,**/*.pyc
            sonar.language=py
            sonar.python.version=3.11
