name: SonarCloud_Git_Actions

on:
  push:
    branches:
      - main
      - pecha

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=backend1
            -Dsonar.projectKey=abrahamramirezT_lambdas_back
            -Dsonar.sources=backEndFinal
            -Dsonar.python.coverage.reportPaths=backEndFinal/coverage.

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: sonarcloud
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Solo despliega en push a la rama main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies for create_incidence
        run: |
          cd backEndFinal/create_incidence/
          pip install -r requirements.txt

      - name: Install dependencies for delete_incidence
        run: |
          cd backEndFinal/delete_incidence/
          pip install -r requirements.txt

      - name: Install dependencies for login
        run: |
          cd backEndFinal/login/

      - name: Install dependencies for read all incidence
        run: |
          cd backEndFinal/read_all_incidence/
          pip install -r requirements.txt

      - name: Install dependencies for read_one_incidence
        run: |
          cd backEndFinal/read_one_incidence/
          pip install -r requirements.txt

      - name: Install dependencies for set_password
        run: |
          cd backEndFinal/set_password/

      - name: Install dependencies for update_incidence
        run: |
          cd backEndFinal/update_incidence/
          pip install -r requirements.txt

      - name: Install dependencies for read_aula_all
        run: |
          cd backEndFinal/read_aula_all/
          pip install -r requirements.txt
          
      - name: Install dependencies for read_div_academica_all
        run: |
          cd backEndFinal/read_div_academica_all/
          pip install -r requirements.txt

      - name: Install dependencies for read_edificio_all
        run: |
          cd backEndFinal/read_edificio_all/
          pip install -r requirements.txt

      - name: Install dependencies for read_grado_all
        run: |
          cd backEndFinal/read_grado_all/
          pip install -r requirements.txt

      - name: Install dependencies for read_grupo_all
        run: |
          cd backEndFinal/read_grupo_all/
          pip install -r requirements.txt
          
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM application
        run: sam build -t backEndFinal/template.yaml

      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name backEnd --capabilities CAPABILITY_IAM 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
