name: SonarCloud_Git_Actions

on:
  push:
    branches:
      - main
      - pecha

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List files
        run: |
          ls -R

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=backend1
            -Dsonar.projectKey=abrahamramirezT_lambdas_back
            -Dsonar.sources=BackEndIncidencias
            -Dsonar.python.coverage.reportPaths=BackEndIncidencias/coverage.

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: sonarcloud
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Solo despliega en push a la rama main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List files
        run: |
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies for create_incidence
        run: |
          if [ -d "create_incidence" ]; then
            cd create_incidence/
            pip install -r requirements.txt
          else
            echo "Directory 'create_incidence' does not exist."
            exit 1
          fi

      - name: Install dependencies for delete_incidence
        run: |
          if [ -d "delete_incidence" ]; then
            cd delete_incidence/
            pip install -r requirements.txt
          else
            echo "Directory 'delete_incidence' does not exist."
            exit 1
          fi

      - name: Install dependencies for login
        run: |
          if [ -d "login" ]; then
            cd login/
            pip install -r requirements.txt
          else
            echo "Directory 'login' does not exist."
            exit 1
          fi

      - name: Install dependencies for read_all_incidence
        run: |
          if [ -d "read_all_incidence" ]; then
            cd read_all_incidence/
            pip install -r requirements.txt
          else
            echo "Directory 'read_all_incidence' does not exist."
            exit 1
          fi

      - name: Install dependencies for read_one_incidence
        run: |
          if [ -d "read_one_incidence" ]; then
            cd read_one_incidence/
            pip install -r requirements.txt
          else
            echo "Directory 'read_one_incidence' does not exist."
            exit 1
          fi

      - name: Install dependencies for set_password
        run: |
          if [ -d "set_password" ]; then
            cd set_password/
            pip install -r requirements.txt
          else
            echo "Directory 'set_password' does not exist."
            exit 1
          fi

      - name: Install dependencies for update_incidence
        run: |
          if [ -d "update_incidence" ]; then
            cd update_incidence/
            pip install -r requirements.txt
          else
            echo "Directory 'update_incidence' does not exist."
            exit 1
          fi

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM application
        run: sam build -t template.yaml

      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name incidenciaIntegradora9A --capabilities CAPABILITY_IAM --resolve-s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
