name: "SonarCloud_Git_Actions"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - name: Change directory to Python folder
        run: cd lambdas_back-main
      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        with:
          args: >
            -Dsonar.organization=backend1
            -Dsonar.projectKey=abrahamramirezT_lambdas_back
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
